server:
    port: 8085
    servlet:
        session:
            timeout: 500m
    tomcat:
        max-http-post-size: 100000000
        max-swallow-size: 100000000


jwt:
  secret: QWERtyuyui
  expiration: 6000000
  header: Authorization
  spring:


spring:
    hateoas:
      use-hal-as-default-json-media-type: false
    data:
      rest:
        base-path: /api
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/home_money?verifyservercertificate=false&useSSL=false&characterEncoding=utf8&characterSetResults=utf8
        username: root
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

